In [1]:
import pandas as pd

# 1) Load CSV
path = "data/suzuki_original-expression.csv"   # change this
df = pd.read_csv(path)

In [2]:
print("Shape (rows, cols):", df.shape)

Shape (rows, cols): (22206, 14)

In [3]:
df.head()

,ID,Public Gene IDs,Gene Symbol,Chromosome,1_(Clariom_S_Mouse).sst-rma-gene-full.chp Signal,2_(Clariom_S_Mouse).sst-rma-gene-full.chp Signal,3_(Clariom_S_Mouse).sst-rma-gene-full.chp Signal,4_(Clariom_S_Mouse).sst-rma-gene-full.chp Signal,5_(Clariom_S_Mouse).sst-rma-gene-full.chp Signal,6_(Clariom_S_Mouse).sst-rma-gene-full.chp Signal,7_(Clariom_S_Mouse).sst-rma-gene-full.chp Signal,8_(Clariom_S_Mouse).sst-rma-gene-full.chp Signal,9_(Clariom_S_Mouse).sst-rma-gene-full.chp Signal,10_(Clariom_S_Mouse).sst-rma-gene-full.chp Signal
0,TC0800000114.mm.2,NM_010172; ENSMUST00000033820; BC061149; OTTMU...,F7,chr8,11.97,11.49,11.56,11.25,11.12,4.54,4.95,5.10,4.98,5.23
1,TC0700001876.mm.2,NM_021334; ENSMUST00000033053; uc009jyb.1; uc0...,Itgax,chr7,12.67,12.35,12.44,12.20,11.41,5.12,5.59,5.27,4.98,6.04
2,TC0200000382.mm.2,NM_001039701; NM_001159562; NM_031167; ENSMUST...,Il1rn,chr2,15.70,14.45,15.79,14.43,14.03,6.52,6.49,6.41,6.42,6.76
3,TC0600002656.mm.2,NM_001037727; NM_001286610; NM_175476; NR_1044...,Arhgap25,chr6,9.35,9.72,8.92,8.98,8.92,5.02,4.82,4.80,5.21,4.88
4,TC0900001142.mm.2,NM_009742; ENSMUST00000098485; uc009qzh.1,Bcl2a1a,chr9,11.94,11.07,11.38,11.13,10.77,6.29,6.66,6.04,6.06,6.03

In [4]:
print("\n🔹 Column names:")
print(df.columns.tolist()[:30], "...")

🔹 Column names:
['ID', 'Public Gene IDs', 'Gene Symbol', 'Chromosome', '1_(Clariom_S_Mouse).sst-rma-gene-full.chp Signal', '2_(Clariom_S_Mouse).sst-rma-gene-full.chp Signal', '3_(Clariom_S_Mouse).sst-rma-gene-full.chp Signal', '4_(Clariom_S_Mouse).sst-rma-gene-full.chp Signal', '5_(Clariom_S_Mouse).sst-rma-gene-full.chp Signal', '6_(Clariom_S_Mouse).sst-rma-gene-full.chp Signal', '7_(Clariom_S_Mouse).sst-rma-gene-full.chp Signal', '8_(Clariom_S_Mouse).sst-rma-gene-full.chp Signal', '9_(Clariom_S_Mouse).sst-rma-gene-full.chp Signal', '10_(Clariom_S_Mouse).sst-rma-gene-full.chp Signal'] ...

In [5]:
first_col = df.columns[0]
print("\n🔹 First column name:", first_col)
print("Example values:", df[first_col].head().tolist())

🔹 First column name: ID
Example values: ['TC0800000114.mm.2', 'TC0700001876.mm.2', 'TC0200000382.mm.2', 'TC0600002656.mm.2', 'TC0900001142.mm.2']

In [6]:
gene_meta = df[["ID", "Public Gene IDs", "Gene Symbol", "Chromosome"]]

expr = df.drop(columns=["ID", "Public Gene IDs", "Gene Symbol", "Chromosome"])

In [7]:
expr.head()

,1_(Clariom_S_Mouse).sst-rma-gene-full.chp Signal,2_(Clariom_S_Mouse).sst-rma-gene-full.chp Signal,3_(Clariom_S_Mouse).sst-rma-gene-full.chp Signal,4_(Clariom_S_Mouse).sst-rma-gene-full.chp Signal,5_(Clariom_S_Mouse).sst-rma-gene-full.chp Signal,6_(Clariom_S_Mouse).sst-rma-gene-full.chp Signal,7_(Clariom_S_Mouse).sst-rma-gene-full.chp Signal,8_(Clariom_S_Mouse).sst-rma-gene-full.chp Signal,9_(Clariom_S_Mouse).sst-rma-gene-full.chp Signal,10_(Clariom_S_Mouse).sst-rma-gene-full.chp Signal
0,11.97,11.49,11.56,11.25,11.12,4.54,4.95,5.10,4.98,5.23
1,12.67,12.35,12.44,12.20,11.41,5.12,5.59,5.27,4.98,6.04
2,15.70,14.45,15.79,14.43,14.03,6.52,6.49,6.41,6.42,6.76
3,9.35,9.72,8.92,8.98,8.92,5.02,4.82,4.80,5.21,4.88
4,11.94,11.07,11.38,11.13,10.77,6.29,6.66,6.04,6.06,6.03

In [8]:
expr_T = expr.T

In [9]:
expr_T.head()

,0,1,2,3,4,5,6,7,8,9,...,22196,22197,22198,22199,22200,22201,22202,22203,22204,22205
1_(Clariom_S_Mouse).sst-rma-gene-full.chp Signal,11.97,12.67,15.70,9.35,11.94,11.27,11.67,9.98,14.32,14.19,...,4.44,6.44,4.15,5.30,3.79,10.15,5.82,4.56,5.14,4.12
2_(Clariom_S_Mouse).sst-rma-gene-full.chp Signal,11.49,12.35,14.45,9.72,11.07,10.80,11.37,9.79,13.69,13.03,...,4.53,6.23,3.82,5.39,3.54,10.07,5.77,4.03,4.62,3.92
3_(Clariom_S_Mouse).sst-rma-gene-full.chp Signal,11.56,12.44,15.79,8.92,11.38,11.48,11.95,10.20,14.18,13.94,...,4.68,6.18,4.55,4.70,3.97,9.93,5.97,4.31,4.58,4.15
4_(Clariom_S_Mouse).sst-rma-gene-full.chp Signal,11.25,12.20,14.43,8.98,11.13,10.99,11.25,10.35,13.73,13.35,...,4.61,6.00,3.59,5.38,3.23,10.41,5.54,4.55,5.09,4.09
5_(Clariom_S_Mouse).sst-rma-gene-full.chp Signal,11.12,11.41,14.03,8.92,10.77,10.32,10.85,9.70,13.69,12.47,...,4.15,6.38,3.73,6.02,3.53,9.90,4.95,5.53,4.77,4.13

In [10]:
print(expr.shape)    # genes × samples
print(expr_T.shape)  # samples × genes

(22206, 10)
(10, 22206)

In [11]:
type(expr_T)

pandas.core.frame.DataFrame

In [15]:
import numpy as np

# expr_T is a pandas DataFrame of shape (10, 22206)

# 1) DataFrame -> numpy (numeric only)
X = expr_T.select_dtypes(include=[np.number]).to_numpy(dtype=np.float32)
print("X shape:", X.shape)

# 2) (recommended) z-score normalize per gene/feature
X = (X - X.mean(axis=0, keepdims=True)) / (X.std(axis=0, keepdims=True) + 1e-6)

# 3) Full SVD
U, S, VT = np.linalg.svd(X, full_matrices=False)
print("U:", U.shape, "S:", S.shape, "VT:", VT.shape)

# 4) Sample embeddings (latent): Z = U * S  (same as U @ diag(S))
Z = U * S
print("Z shape (full rank):", Z.shape)  # (10, 10)

pd.DataFrame(Z).to_csv("data/suzukiSVDcsv.csv", index=False)

X shape: (10, 22206)
U: (10, 10) S: (10,) VT: (10, 22206)
Z shape (full rank): (10, 10)

In [16]:
pd.DataFrame(expr_T).to_csv("data/suzukicsv.csv", index=False)